version: '3.8'

services:
  copilot-runtime-dev:
    build:
      context: .
      dockerfile: dockerfile
      target: builder  # Use builder stage for development
    container_name: copilot-runtime-dev
    ports:
      - "4000:4000"
      - "9229:9229"  # Node.js debugger port
    
    env_file:
      - .env
    
    # Development: mount source code for live reload
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    
    # Override the default command for development
    command: npm run dev
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    networks:
      - copilot-network

  # Optional: Add a simple web UI for testing
  # copilot-ui:
  #   image: nginx:alpine
  #   container_name: copilot-ui-dev
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./public:/usr/share/nginx/html:ro
  #   networks:
  #     - copilot-network
  #   depends_on:
  #     - copilot-runtime-dev

networks:
  copilot-network:
    driver: bridge 